[package]
name = "aoc-2019-rust"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num-traits = "0.2.15"
regex = "1.7.0"
reqwest = { version = "0.11.13", features = ["cookies", "blocking"] }
