set windows-shell := ["pwsh.exe", "-NoLogo", "-Command"]

new:
    python3 -c "from tasks import copy_template; copy_template()"
run:
    python3 -c "from tasks import run_latest; run_latest()"
test:
    python3 -c "from tasks import test_latest; test_latest()"
web:
    python3 -c "from tasks import open_web; open_web()"